In [1]:
import numpy as np
import pandas as pd

In [2]:
activity = pd.read_csv('datasets/movie-metrics/activity.csv', parse_dates=['date'])
users = pd.read_csv('datasets/movie-metrics/users.csv', parse_dates=['created_at'])

# Method 1: proper and simplistic version

In [3]:
started_finished = (
    activity
    .groupby('user_id')['finished']
    .agg(['count', 'sum'])
    .rename(columns={
        'count': 'started',
        'sum': 'finished'
    })
)

In [4]:
first_movies = activity[activity['finished'] == 1].groupby('user_id').first() \
    .rename(columns={'movie_name': 'first_movie', 'date': 'first_date'}) \
    .drop(columns=['finished', 'id'])
last_movies = activity[activity['finished'] == 1].groupby('user_id').last() \
    .rename(columns={'movie_name': 'last_movie', 'date': 'last_date'}) \
    .drop(columns=['finished', 'id'])

In [5]:
# Most of these groupby queries return with index so that pd.concat matches without many params
# This might be getting overwhelmed for beginners if they have not glanced over the whole documentation
user_summary = pd.concat([first_movies, last_movies, started_finished], axis='columns').reset_index()

In [6]:
user_summary

,user_id,first_date,first_movie,last_date,last_movie,started,finished
0,1,2023-09-12,Turning Red,2025-03-26,Her,30,26
1,2,2023-06-22,The Shawshank Redemption,2025-05-01,Fight Club,15,12
2,3,2023-11-10,Oppenheimer,2025-03-31,Nope,10,7
3,4,2023-07-27,Fight Club,2025-05-09,Avengers: Endgame,43,34
4,5,2023-09-07,Top Gun: Maverick,2025-03-14,Bohemian Rhapsody,31,25
5,6,2023-12-18,Inception,2025-03-27,The Revenant,13,11
6,7,2024-08-28,Avengers: Endgame,2024-09-15,Soul,2,2
7,8,2024-01-24,Arrival,2025-04-25,Whiplash,29,23
8,9,2024-02-25,Big Hero 6,2025-04-11,Moonlight,17,12
9,10,2024-05-01,Whiplash,2025-03-08,Knives Out,7,6
10,11,2025-01-29,Avengers: Endgame,2025-01-29,Avengers: Endgame,2,1
11,12,2024-04-11,Get Out,2025-05-08,Inside Out,46,38
12,13,2024-09-19,Bohemian Rhapsody,2025-05-16,Soul,5,5
13,14,2024-09-29,Spider-Man: No Way Home,2025-05-10,Parasite,14,12
14,15,2024-09-21,Dune,2025-05-05,Forrest Gump,20,14
15,16,2024-10-12,Everything Everywhere All At Once,2025-04-30,Parasite,29,21
16,17,2024-09-01,Forrest Gump,2025-05-11,Shrek,23,19
17,18,2024-10-01,Fight Club,2025-05-16,Fight Club,35,28
18,19,2024-12-21,The Social Network,2025-05-14,Coco,20,14
19,20,2024-11-27,Luca,2025-05-02,Fight Club,34,19
20,21,2025-01-03,Up,2025-05-14,Forrest Gump,35,29
21,22,2025-01-14,Knives Out,2025-05-13,Big Hero 6,36,28
22,23,2025-01-31,Gladiator,2025-05-04,Mad Max: Fury Road,24,17
23,24,2025-02-05,Dune,2025-05-16,The Social Network,17,17
24,25,2025-04-07,Spider-Man: No Way Home,2025-05-10,Bohemian Rhapsody,23,17

## How many users have "Fight Club" as the last film they've seen?

In [7]:
user_summary.query('last_movie == "Fight Club"')

,user_id,first_date,first_movie,last_date,last_movie,started,finished
1,2,2023-06-22,The Shawshank Redemption,2025-05-01,Fight Club,15,12
17,18,2024-10-01,Fight Club,2025-05-16,Fight Club,35,28
19,20,2024-11-27,Luca,2025-05-02,Fight Club,34,19

# Method 2: returns multiple values with the same date

In [8]:
num_finished = (
    activity
    .groupby('user_id')['finished']
    .agg(['count', 'sum'])
    .rename(columns={
        'count': 'started',
        'sum': 'finished'
    })
)

In [9]:
first_and_last = (
    activity[activity['finished'] == 1]
    .groupby('user_id')['date']
    .agg(['min','max'])
    .rename(columns={
        'min':'first_date',
        'max': 'last_date'
    })
)

In [10]:
user_summary = (
    pd.concat([first_and_last, num_finished], axis='columns')
    .reset_index()
    .merge(activity, left_on=['user_id', 'first_date'], right_on=['user_id', 'date'])
    .merge(activity, left_on=['user_id', 'last_date'], right_on=['user_id', 'date'])
)
user_summary = user_summary[[
    'user_id',
    'first_date', 'movie_name_x',
    'last_date', 'movie_name_y',
    'started', 'finished_x'
]].rename(columns={
    'movie_name_x': 'first_movie',
    'movie_name_y': 'last_movie',
    'finished_x': 'finished'
})

In [11]:
user_summary

,user_id,first_date,first_movie,last_date,last_movie,started,finished
0,1,2023-09-12,Turning Red,2025-03-26,Her,30,26
1,2,2023-06-22,The Shawshank Redemption,2025-05-01,Fight Club,15,12
2,3,2023-11-10,Oppenheimer,2025-03-31,Nope,10,7
3,4,2023-07-27,Fight Club,2025-05-09,Avengers: Endgame,43,34
4,5,2023-09-07,Top Gun: Maverick,2025-03-14,Bohemian Rhapsody,31,25
5,6,2023-12-18,Inception,2025-03-27,The Revenant,13,11
6,7,2024-08-28,Avengers: Endgame,2024-09-15,Soul,2,2
7,8,2024-01-24,Arrival,2025-04-25,Whiplash,29,23
8,9,2024-02-25,Big Hero 6,2025-04-11,Moonlight,17,12
9,10,2024-05-01,Whiplash,2025-03-08,Knives Out,7,6
10,11,2025-01-29,Avengers: Endgame,2025-01-29,Avengers: Endgame,2,1
11,12,2024-04-11,Get Out,2025-05-08,Inside Out,46,38
12,13,2024-09-19,Bohemian Rhapsody,2025-05-16,Soul,5,5
13,14,2024-09-29,Spider-Man: No Way Home,2025-05-10,Parasite,14,12
14,15,2024-09-21,Dune,2025-05-05,Forrest Gump,20,14
15,16,2024-10-12,Everything Everywhere All At Once,2025-04-30,Minari,29,21
16,16,2024-10-12,Everything Everywhere All At Once,2025-04-30,Parasite,29,21
17,17,2024-09-01,Forrest Gump,2025-05-11,Big Hero 6,23,19
18,17,2024-09-01,Forrest Gump,2025-05-11,Shrek,23,19
19,18,2024-10-01,Fight Club,2025-05-16,Fight Club,35,28
20,19,2024-12-21,The Social Network,2025-05-14,Coco,20,14
21,20,2024-11-27,Luca,2025-05-02,Fight Club,34,19
22,20,2024-11-27,The Wolf of Wall Street,2025-05-02,Fight Club,34,19
23,21,2025-01-03,Up,2025-05-14,Forrest Gump,35,29
24,22,2025-01-14,Knives Out,2025-05-13,Big Hero 6,36,28
25,23,2025-01-31,Gladiator,2025-05-04,Mad Max: Fury Road,24,17
26,24,2025-02-05,Dune,2025-05-16,The Social Network,17,17
27,25,2025-04-07,Spider-Man: No Way Home,2025-05-10,Bohemian Rhapsody,23,17

In [12]:
user_summary.query('last_movie == "Fight Club"')

,user_id,first_date,first_movie,last_date,last_movie,started,finished
1,2,2023-06-22,The Shawshank Redemption,2025-05-01,Fight Club,15,12
19,18,2024-10-01,Fight Club,2025-05-16,Fight Club,35,28
21,20,2024-11-27,Luca,2025-05-02,Fight Club,34,19
22,20,2024-11-27,The Wolf of Wall Street,2025-05-02,Fight Club,34,19