In [1]:
import numpy as np
import pandas as pd
pd.set_option('display.max_rows', None)
pd.set_option('display.min_rows', None)

In [2]:
promotions = pd.read_csv('datasets/promotions/promotions.csv', parse_dates=['start_date','end_date'])
orders = pd.read_csv('datasets/promotions/orders.csv', parse_dates=['order_date'])

In [3]:
promotions

  promo_id        promo_name start_date   end_date
0  BF_2023      Black Friday 2023-11-24 2023-11-29
1  NY_2024     New Year Sale 2024-01-01 2024-01-07
2  SB_2024    Summer Blowout 2024-07-15 2024-07-31
3  BF_2024      Black Friday 2024-11-25 2024-11-30
4  NY_2025     New Year Sale 2025-01-01 2025-01-07
5  SC_2025  Spring Clearance 2025-03-10 2025-03-20

In [4]:
orders.head()

   order_id order_date  order_quantity
0         1 2023-05-01               2
1         2 2023-05-01               3
2         3 2023-05-01               1
3         4 2023-05-01               5
4         5 2023-05-01               2

# Method 1: Using merge_asof

In [6]:
df = pd.merge_asof(
    orders.sort_values('order_date'),
    promotions.sort_values('start_date'),
    left_on='order_date',
    right_on='start_date',
    direction='backward'
)
df.loc[df['order_date'] > df['end_date'], 'promo_id'] = np.nan
df[['order_id','order_date','order_quantity','promo_id']]

      order_id order_date  order_quantity promo_id
0            1 2023-05-01               2      NaN
1            2 2023-05-01               3      NaN
2            3 2023-05-01               1      NaN
3            4 2023-05-01               5      NaN
4            5 2023-05-01               2      NaN
5            6 2023-05-02               2      NaN
6            7 2023-05-02               4      NaN
7            8 2023-05-02               4      NaN
8            9 2023-05-02               3      NaN
9           10 2023-05-03               2      NaN
10          11 2023-05-03               3      NaN
11          16 2023-05-04               3      NaN
12          14 2023-05-04               3      NaN
13          15 2023-05-04               4      NaN
14          12 2023-05-04               2      NaN
15          13 2023-05-04               2      NaN
16          17 2023-05-05               1      NaN
17          18 2023-05-06               5      NaN
18          19 2023-05-06               2      NaN
19          20 2023-05-06               5      NaN
20          21 2023-05-06               1      NaN
21          22 2023-05-06               2      NaN
22          23 2023-05-07               1      NaN
23          24 2023-05-07               6      NaN
24          25 2023-05-07               1      NaN
25          26 2023-05-07               1      NaN
26          29 2023-05-08               2      NaN
27          27 2023-05-08               3      NaN
28          28 2023-05-08               5      NaN
29          33 2023-05-09               3      NaN
30          32 2023-05-09               1      NaN
31          30 2023-05-09               3      NaN
32          31 2023-05-09               4      NaN
33          34 2023-05-10               3      NaN
34          35 2023-05-10               4      NaN
35          36 2023-05-10               5      NaN
36          37 2023-05-10               6      NaN
37          40 2023-05-11               3      NaN
38          38 2023-05-11               3      NaN
39          39 2023-05-11               5      NaN
40          41 2023-05-11               5      NaN
41          42 2023-05-11               3      NaN
42          43 2023-05-11               4      NaN
43          44 2023-05-12               4      NaN
44          47 2023-05-13               4      NaN
45          46 2023-05-13               5      NaN
46          45 2023-05-13               4      NaN
47          52 2023-05-14               3      NaN
48          51 2023-05-14               4      NaN
49          48 2023-05-14               5      NaN
50          49 2023-05-14               1      NaN
51          50 2023-05-14               2      NaN
52          53 2023-05-15               5      NaN
53          54 2023-05-15               3      NaN
54          55 2023-05-15               1      NaN
55          60 2023-05-16               1      NaN
56          56 2023-05-16               8      NaN
57          57 2023-05-16               6      NaN
58          58 2023-05-16               5      NaN
59          59 2023-05-16               2      NaN
60          61 2023-05-16               3      NaN
61          63 2023-05-17               4      NaN
62          62 2023-05-17               2      NaN
63          66 2023-05-18               3      NaN
64          65 2023-05-18               6      NaN
65          64 2023-05-18               6      NaN
66          67 2023-05-19               4      NaN
67          68 2023-05-19               2      NaN
68          69 2023-05-20               1      NaN
69          70 2023-05-20               7      NaN
70          71 2023-05-20               5      NaN
71          72 2023-05-20               1      NaN
72          73 2023-05-20               3      NaN
73          74 2023-05-21               1      NaN
74          75 2023-05-21               3      NaN
75          76 2023-05-21               4      NaN
76          77 2023-05-21               4      NaN
77          81 2023-05-22               1      NaN
78          80 2023-05-22               4      NaN
79          78 2023-05-22               2      NaN
80          79 2023-05-22               3      NaN
81          82 2023-05-23               5      NaN
82          83 2023-05-24               2      NaN
83          84 2023-05-24               2      NaN
84          85 2023-05-24               1      NaN
85          86 2023-05-24               5      NaN
86          87 2023-05-25               1      NaN
87          88 2023-05-25               6      NaN
88          89 2023-05-25               3      NaN
89          90 2023-05-26               2      NaN
90          91 2023-05-26               4      NaN
91          92 2023-05-26               2      NaN
92          96 2023-05-27               1      NaN
93          95 2023-05-27               4      NaN
94          97 2023-05-27               1      NaN
95          93 2023-05-27               4      NaN
96          94 2023-05-27               2      NaN
97          98 2023-05-28               2      NaN
98          99 2023-05-28               3      NaN
99         100 2023-05-28               4      NaN
100        101 2023-05-28               2      NaN
101        102 2023-05-28               7      NaN
102        103 2023-05-28               3      NaN
103        104 2023-05-30               7      NaN
104        105 2023-05-31               6      NaN
105        106 2023-06-01               1      NaN
106        107 2023-06-01               4      NaN
107        108 2023-06-01               1      NaN
108        109 2023-06-02               3      NaN
109        110 2023-06-02               1      NaN
110        111 2023-06-02               5      NaN
111        115 2023-06-03               9      NaN
112        114 2023-06-03               6      NaN
113        112 2023-06-03               2      NaN
114        113 2023-06-03               2      NaN
115        116 2023-06-04               3      NaN
116        117 2023-06-04               6      NaN
117        118 2023-06-04               1      NaN
118        119 2023-06-05               2      NaN
119        120 2023-06-05               2      NaN
120        121 2023-06-05               7      NaN
121        122 2023-06-05               1      NaN
122        123 2023-06-06               4      NaN
123        124 2023-06-06               2      NaN
124        131 2023-06-07               1      NaN
125        134 2023-06-07               4      NaN
126        133 2023-06-07               3      NaN
127        132 2023-06-07               4      NaN
128        130 2023-06-07               1      NaN
129        129 2023-06-07               3      NaN
130        128 2023-06-07               2      NaN
131        127 2023-06-07               5      NaN
132        126 2023-06-07               4      NaN
133        125 2023-06-07               3      NaN
134        135 2023-06-08               6      NaN
135        136 2023-06-08               3      NaN
136        137 2023-06-08               3      NaN
137        138 2023-06-08               1      NaN
138        139 2023-06-08               2      NaN
139        140 2023-06-09               1      NaN
140        141 2023-06-09               2      NaN
141        142 2023-06-09               2      NaN
142        143 2023-06-09               3      NaN
143        147 2023-06-10               3      NaN
144        146 2023-06-10               2      NaN
145        144 2023-06-10               3      NaN
146        145 2023-06-10               5      NaN
147        148 2023-06-11               2      NaN
148        149 2023-06-11               4      NaN
149        150 2023-06-11               5      NaN
150        151 2023-06-12               1      NaN
151        152 2023-06-14               1      NaN
152        153 2023-06-14               3      NaN
153        154 2023-06-14               2      NaN
154        155 2023-06-14               3      NaN
155        160 2023-06-15               4      NaN
156        162 2023-06-15               3      NaN
157        159 2023-06-15               2      NaN
158        161 2023-06-15               2      NaN
159        157 2023-06-15               2      NaN
160        158 2023-06-15               2      NaN
161        156 2023-06-15               4      NaN
162        163 2023-06-16               3      NaN
163        164 2023-06-16               2      NaN
164        165 2023-06-17               2      NaN
165        166 2023-06-17               2      NaN
166        167 2023-06-17               3      NaN
167        168 2023-06-18               7      NaN
168        169 2023-06-19               1      NaN
169        170 2023-06-19               1      NaN
170        171 2023-06-19               1      NaN
171        172 2023-06-19               3      NaN
172        173 2023-06-19               1      NaN
173        174 2023-06-19               4      NaN
174        180 2023-06-21               2      NaN
175        179 2023-06-21               4      NaN
176        178 2023-06-21               8      NaN
177        175 2023-06-21               6      NaN
178        176 2023-06-21               2      NaN
179        177 2023-06-21               2      NaN
180        181 2023-06-22               3      NaN
181        182 2023-06-22               1      NaN
182        183 2023-06-22               2      NaN
183        184 2023-06-22               2      NaN
184        185 2023-06-22               7      NaN
185        186 2023-06-23               3      NaN
186        187 2023-06-23               4      NaN
187        188 2023-06-23               3      NaN
188        190 2023-06-24               2      NaN
189        189 2023-06-24               3      NaN
190        193 2023-06-26               3      NaN
191        194 2023-06-26               3      NaN
192        191 2023-06-26               1      NaN
193        192 2023-06-26               4      NaN
194        195 2023-06-27               4      NaN
195        196 2023-06-27               2      NaN
196        197 2023-06-27               5      NaN
197        198 2023-06-28               4      NaN
198        199 2023-06-28               2      NaN
199        200 2023-06-29               3      NaN
200        201 2023-06-29               1      NaN
201        202 2023-06-30               4      NaN
202        203 2023-06-30               2      NaN
203        204 2023-06-30               3      NaN
204        207 2023-07-01               2      NaN
205        208 2023-07-01               2      NaN
206        205 2023-07-01               2      NaN
207        206 2023-07-01               4      NaN
208        209 2023-07-02               3      NaN
209        210 2023-07-03               4      NaN
210        211 2023-07-03               2      NaN
211        212 2023-07-03               7      NaN
212        213 2023-07-04               5      NaN
213        214 2023-07-05               2      NaN
214        216 2023-07-07               1      NaN
215        217 2023-07-07               3      NaN
216        218 2023-07-07               1      NaN
217        219 2023-07-07               1      NaN
218        220 2023-07-07               2      NaN
219        215 2023-07-07               4      NaN
220        221 2023-07-08               5      NaN
221        223 2023-07-10               2      NaN
222        222 2023-07-10               1      NaN
223        226 2023-07-11               3      NaN
224        225 2023-07-11               5      NaN
225        224 2023-07-11               6      NaN
226        227 2023-07-12               3      NaN
227        228 2023-07-13               1      NaN
228        229 2023-07-13               7      NaN
229        230 2023-07-13               1      NaN
230        231 2023-07-13               1      NaN
231        232 2023-07-13               6      NaN
232        233 2023-07-13               1      NaN
233        234 2023-07-14               7      NaN
234        235 2023-07-14               2      NaN
235        236 2023-07-14               4      NaN
236        241 2023-07-16               1      NaN
237        240 2023-07-16               4      NaN
238        239 2023-07-16               6      NaN
239        238 2023-07-16               3      NaN
240        237 2023-07-16               3      NaN
241        242 2023-07-17               1      NaN
242        243 2023-07-18               1      NaN
243        244 2023-07-19               4      NaN
244        245 2023-07-19               2      NaN
245        246 2023-07-19               2      NaN
246        247 2023-07-20               2      NaN
247        248 2023-07-20               6      NaN
248        249 2023-07-21               5      NaN
249        255 2023-07-22               4      NaN
250        254 2023-07-22               1      NaN
251        253 2023-07-22               1      NaN
252        256 2023-07-22               1      NaN
253        251 2023-07-22               4      NaN
254        250 2023-07-22               3      NaN
255        252 2023-07-22               3      NaN
256        259 2023-07-23               4      NaN
257        258 2023-07-23               5      NaN
258        257 2023-07-23               2      NaN
259        260 2023-07-24               2      NaN
260        261 2023-07-24               2      NaN
261        262 2023-07-24               3      NaN
262        263 2023-07-24               2      NaN
263        264 2023-07-24               2      NaN
264        265 2023-07-25               4      NaN
265        266 2023-07-25               4      NaN
266        267 2023-07-26               2      NaN
267        268 2023-07-26               2      NaN
268        269 2023-07-27               4      NaN
269        270 2023-07-27               4      NaN
270        271 2023-07-27               2      NaN
271        272 2023-07-27               3      NaN
272        276 2023-07-28               4      NaN
273        275 2023-07-28               5      NaN
274        273 2023-07-28               3      NaN
275        274 2023-07-28               3      NaN
276        277 2023-07-29               2      NaN
277        278 2023-07-30               3      NaN
278        279 2023-07-30               3      NaN
279        280 2023-07-31               2      NaN
280        281 2023-07-31               1      NaN
281        282 2023-08-01               8      NaN
282        283 2023-08-02               1      NaN
283        284 2023-08-02               5      NaN
284        287 2023-08-03               4      NaN
285        285 2023-08-03               4      NaN
286        286 2023-08-03               1      NaN
287        288 2023-08-03               2      NaN
288        289 2023-08-04               2      NaN
289        290 2023-08-05               5      NaN
290        291 2023-08-05               3      NaN
291        292 2023-08-05               2      NaN
292        301 2023-08-06               2      NaN
293        300 2023-08-06               2      NaN
294        299 2023-08-06               6      NaN
295        297 2023-08-06               5      NaN
296        298 2023-08-06               3      NaN
297        295 2023-08-06               1      NaN
298        294 2023-08-06               3      NaN
299        293 2023-08-06               5      NaN
300        296 2023-08-06               4      NaN
301        302 2023-08-07               2      NaN
302        303 2023-08-07               2      NaN
303        304 2023-08-07               1      NaN
304        308 2023-08-09               3      NaN
305        307 2023-08-09               3      NaN
306        305 2023-08-09               2      NaN
307        306 2023-08-09               2      NaN
308        309 2023-08-10               5      NaN
309        310 2023-08-10               1      NaN
310        311 2023-08-10               1      NaN
311        312 2023-08-10               2      NaN
312        313 2023-08-11               4      NaN
313        314 2023-08-11               5      NaN
314        315 2023-08-12               4      NaN
315        319 2023-08-13               1      NaN
316        316 2023-08-13               4      NaN
317        317 2023-08-13               2      NaN
318        318 2023-08-13               4      NaN
319        323 2023-08-14               3      NaN
320        322 2023-08-14               3      NaN
321        320 2023-08-14               1      NaN
322        321 2023-08-14               4      NaN
323        324 2023-08-15               1      NaN
324        325 2023-08-15               5      NaN
325        326 2023-08-15               3      NaN
326        327 2023-08-16               2      NaN
327        328 2023-08-16               2      NaN
328        329 2023-08-16               3      NaN
329        330 2023-08-18               2      NaN
330        331 2023-08-18               2      NaN
331        332 2023-08-18               3      NaN
332        333 2023-08-18               3      NaN
333        334 2023-08-19               4      NaN
334        340 2023-08-20               5      NaN
335        339 2023-08-20               6      NaN
336        338 2023-08-20               4      NaN
337        335 2023-08-20               3      NaN
338        336 2023-08-20               8      NaN
339        337 2023-08-20               2      NaN
340        341 2023-08-21               1      NaN
341        342 2023-08-21               3      NaN
342        343 2023-08-21               1      NaN
343        346 2023-08-22               1      NaN
344        344 2023-08-22               2      NaN
345        345 2023-08-22               1      NaN
346        347 2023-08-23               3      NaN
347        353 2023-08-24               6      NaN
348        351 2023-08-24               4      NaN
349        352 2023-08-24               5      NaN
350        349 2023-08-24               3      NaN
351        348 2023-08-24               4      NaN
352        350 2023-08-24               2      NaN
353        354 2023-08-25               2      NaN
354        355 2023-08-25               4      NaN
355        356 2023-08-25               3      NaN
356        357 2023-08-25               5      NaN
357        358 2023-08-25               2      NaN
358        359 2023-08-25               5      NaN
359        360 2023-08-26               4      NaN
360        361 2023-08-26               1      NaN
361        362 2023-08-26               1      NaN
362        367 2023-08-27               3      NaN
363        365 2023-08-27               3      NaN
364        366 2023-08-27               2      NaN
365        363 2023-08-27               1      NaN
366        364 2023-08-27               4      NaN
367        368 2023-08-28               3      NaN
368        369 2023-08-28               4      NaN
369        370 2023-08-29               2      NaN
370        371 2023-08-29               4      NaN
371        372 2023-08-29               3      NaN
372        373 2023-08-30               3      NaN
373        375 2023-08-31               6      NaN
374        374 2023-08-31               3      NaN
375        376 2023-09-01               2      NaN
376        377 2023-09-02               3      NaN
377        378 2023-09-02               3      NaN
378        379 2023-09-02               4      NaN
379        380 2023-09-03               3      NaN
380        381 2023-09-03               4      NaN
381        382 2023-09-03               2      NaN
382        384 2023-09-04               3      NaN
383        383 2023-09-04               2      NaN
384        385 2023-09-04               2      NaN
385        387 2023-09-05               4      NaN
386        386 2023-09-05               5      NaN
387        388 2023-09-06               2      NaN
388        389 2023-09-06               4      NaN
389        390 2023-09-06               2      NaN
390        391 2023-09-06               1      NaN

In [7]:
df['promo_id'].isna().sum()

1916

# Method 2: Using IntervalIndex

In [8]:
intervals = pd.IntervalIndex.from_arrays(
    promotions['start_date'], promotions['end_date'], closed='both'
)
idx = intervals.get_indexer(orders["order_date"])
data2_matched = promotions.iloc[idx].reset_index(drop=True)
data2_matched.index = orders.index

no_match = idx == -1
df = orders.copy()
df['promo_id'] = data2_matched['promo_id'].where(~pd.Series(no_match, index=orders.index))
df[['start_date', 'end_date']] = data2_matched[['start_date', 'end_date']].where(
    ~pd.Series(no_match, index=orders.index)
)

df

      order_id order_date  order_quantity promo_id start_date   end_date
0            1 2023-05-01               2      NaN        NaT        NaT
1            2 2023-05-01               3      NaN        NaT        NaT
2            3 2023-05-01               1      NaN        NaT        NaT
3            4 2023-05-01               5      NaN        NaT        NaT
4            5 2023-05-01               2      NaN        NaT        NaT
5            6 2023-05-02               2      NaN        NaT        NaT
6            7 2023-05-02               4      NaN        NaT        NaT
7            8 2023-05-02               4      NaN        NaT        NaT
8            9 2023-05-02               3      NaN        NaT        NaT
9           10 2023-05-03               2      NaN        NaT        NaT
10          11 2023-05-03               3      NaN        NaT        NaT
11          12 2023-05-04               2      NaN        NaT        NaT
12          13 2023-05-04               2      NaN        NaT        NaT
13          14 2023-05-04               3      NaN        NaT        NaT
14          15 2023-05-04               4      NaN        NaT        NaT
15          16 2023-05-04               3      NaN        NaT        NaT
16          17 2023-05-05               1      NaN        NaT        NaT
17          18 2023-05-06               5      NaN        NaT        NaT
18          19 2023-05-06               2      NaN        NaT        NaT
19          20 2023-05-06               5      NaN        NaT        NaT
20          21 2023-05-06               1      NaN        NaT        NaT
21          22 2023-05-06               2      NaN        NaT        NaT
22          23 2023-05-07               1      NaN        NaT        NaT
23          24 2023-05-07               6      NaN        NaT        NaT
24          25 2023-05-07               1      NaN        NaT        NaT
25          26 2023-05-07               1      NaN        NaT        NaT
26          27 2023-05-08               3      NaN        NaT        NaT
27          28 2023-05-08               5      NaN        NaT        NaT
28          29 2023-05-08               2      NaN        NaT        NaT
29          30 2023-05-09               3      NaN        NaT        NaT
30          31 2023-05-09               4      NaN        NaT        NaT
31          32 2023-05-09               1      NaN        NaT        NaT
32          33 2023-05-09               3      NaN        NaT        NaT
33          34 2023-05-10               3      NaN        NaT        NaT
34          35 2023-05-10               4      NaN        NaT        NaT
35          36 2023-05-10               5      NaN        NaT        NaT
36          37 2023-05-10               6      NaN        NaT        NaT
37          38 2023-05-11               3      NaN        NaT        NaT
38          39 2023-05-11               5      NaN        NaT        NaT
39          40 2023-05-11               3      NaN        NaT        NaT
40          41 2023-05-11               5      NaN        NaT        NaT
41          42 2023-05-11               3      NaN        NaT        NaT
42          43 2023-05-11               4      NaN        NaT        NaT
43          44 2023-05-12               4      NaN        NaT        NaT
44          45 2023-05-13               4      NaN        NaT        NaT
45          46 2023-05-13               5      NaN        NaT        NaT
46          47 2023-05-13               4      NaN        NaT        NaT
47          48 2023-05-14               5      NaN        NaT        NaT
48          49 2023-05-14               1      NaN        NaT        NaT
49          50 2023-05-14               2      NaN        NaT        NaT
50          51 2023-05-14               4      NaN        NaT        NaT
51          52 2023-05-14               3      NaN        NaT        NaT
52          53 2023-05-15               5      NaN        NaT        NaT
53          54 2023-05-15               3      NaN        NaT        NaT
54          55 2023-05-15               1      NaN        NaT        NaT
55          56 2023-05-16               8      NaN        NaT        NaT
56          57 2023-05-16               6      NaN        NaT        NaT
57          58 2023-05-16               5      NaN        NaT        NaT
58          59 2023-05-16               2      NaN        NaT        NaT
59          60 2023-05-16               1      NaN        NaT        NaT
60          61 2023-05-16               3      NaN        NaT        NaT
61          62 2023-05-17               2      NaN        NaT        NaT
62          63 2023-05-17               4      NaN        NaT        NaT
63          64 2023-05-18               6      NaN        NaT        NaT
64          65 2023-05-18               6      NaN        NaT        NaT
65          66 2023-05-18               3      NaN        NaT        NaT
66          67 2023-05-19               4      NaN        NaT        NaT
67          68 2023-05-19               2      NaN        NaT        NaT
68          69 2023-05-20               1      NaN        NaT        NaT
69          70 2023-05-20               7      NaN        NaT        NaT
70          71 2023-05-20               5      NaN        NaT        NaT
71          72 2023-05-20               1      NaN        NaT        NaT
72          73 2023-05-20               3      NaN        NaT        NaT
73          74 2023-05-21               1      NaN        NaT        NaT
74          75 2023-05-21               3      NaN        NaT        NaT
75          76 2023-05-21               4      NaN        NaT        NaT
76          77 2023-05-21               4      NaN        NaT        NaT
77          78 2023-05-22               2      NaN        NaT        NaT
78          79 2023-05-22               3      NaN        NaT        NaT
79          80 2023-05-22               4      NaN        NaT        NaT
80          81 2023-05-22               1      NaN        NaT        NaT
81          82 2023-05-23               5      NaN        NaT        NaT
82          83 2023-05-24               2      NaN        NaT        NaT
83          84 2023-05-24               2      NaN        NaT        NaT
84          85 2023-05-24               1      NaN        NaT        NaT
85          86 2023-05-24               5      NaN        NaT        NaT
86          87 2023-05-25               1      NaN        NaT        NaT
87          88 2023-05-25               6      NaN        NaT        NaT
88          89 2023-05-25               3      NaN        NaT        NaT
89          90 2023-05-26               2      NaN        NaT        NaT
90          91 2023-05-26               4      NaN        NaT        NaT
91          92 2023-05-26               2      NaN        NaT        NaT
92          93 2023-05-27               4      NaN        NaT        NaT
93          94 2023-05-27               2      NaN        NaT        NaT
94          95 2023-05-27               4      NaN        NaT        NaT
95          96 2023-05-27               1      NaN        NaT        NaT
96          97 2023-05-27               1      NaN        NaT        NaT
97          98 2023-05-28               2      NaN        NaT        NaT
98          99 2023-05-28               3      NaN        NaT        NaT
99         100 2023-05-28               4      NaN        NaT        NaT
100        101 2023-05-28               2      NaN        NaT        NaT
101        102 2023-05-28               7      NaN        NaT        NaT
102        103 2023-05-28               3      NaN        NaT        NaT
103        104 2023-05-30               7      NaN        NaT        NaT
104        105 2023-05-31               6      NaN        NaT        NaT
105        106 2023-06-01               1      NaN        NaT        NaT
106        107 2023-06-01               4      NaN        NaT        NaT
107        108 2023-06-01               1      NaN        NaT        NaT
108        109 2023-06-02               3      NaN        NaT        NaT
109        110 2023-06-02               1      NaN        NaT        NaT
110        111 2023-06-02               5      NaN        NaT        NaT
111        112 2023-06-03               2      NaN        NaT        NaT
112        113 2023-06-03               2      NaN        NaT        NaT
113        114 2023-06-03               6      NaN        NaT        NaT
114        115 2023-06-03               9      NaN        NaT        NaT
115        116 2023-06-04               3      NaN        NaT        NaT
116        117 2023-06-04               6      NaN        NaT        NaT
117        118 2023-06-04               1      NaN        NaT        NaT
118        119 2023-06-05               2      NaN        NaT        NaT
119        120 2023-06-05               2      NaN        NaT        NaT
120        121 2023-06-05               7      NaN        NaT        NaT
121        122 2023-06-05               1      NaN        NaT        NaT
122        123 2023-06-06               4      NaN        NaT        NaT
123        124 2023-06-06               2      NaN        NaT        NaT
124        125 2023-06-07               3      NaN        NaT        NaT
125        126 2023-06-07               4      NaN        NaT        NaT
126        127 2023-06-07               5      NaN        NaT        NaT
127        128 2023-06-07               2      NaN        NaT        NaT
128        129 2023-06-07               3      NaN        NaT        NaT
129        130 2023-06-07               1      NaN        NaT        NaT
130        131 2023-06-07               1      NaN        NaT        NaT
131        132 2023-06-07               4      NaN        NaT        NaT
132        133 2023-06-07               3      NaN        NaT        NaT
133        134 2023-06-07               4      NaN        NaT        NaT
134        135 2023-06-08               6      NaN        NaT        NaT
135        136 2023-06-08               3      NaN        NaT        NaT
136        137 2023-06-08               3      NaN        NaT        NaT
137        138 2023-06-08               1      NaN        NaT        NaT
138        139 2023-06-08               2      NaN        NaT        NaT
139        140 2023-06-09               1      NaN        NaT        NaT
140        141 2023-06-09               2      NaN        NaT        NaT
141        142 2023-06-09               2      NaN        NaT        NaT
142        143 2023-06-09               3      NaN        NaT        NaT
143        144 2023-06-10               3      NaN        NaT        NaT
144        145 2023-06-10               5      NaN        NaT        NaT
145        146 2023-06-10               2      NaN        NaT        NaT
146        147 2023-06-10               3      NaN        NaT        NaT
147        148 2023-06-11               2      NaN        NaT        NaT
148        149 2023-06-11               4      NaN        NaT        NaT
149        150 2023-06-11               5      NaN        NaT        NaT
150        151 2023-06-12               1      NaN        NaT        NaT
151        152 2023-06-14               1      NaN        NaT        NaT
152        153 2023-06-14               3      NaN        NaT        NaT
153        154 2023-06-14               2      NaN        NaT        NaT
154        155 2023-06-14               3      NaN        NaT        NaT
155        156 2023-06-15               4      NaN        NaT        NaT
156        157 2023-06-15               2      NaN        NaT        NaT
157        158 2023-06-15               2      NaN        NaT        NaT
158        159 2023-06-15               2      NaN        NaT        NaT
159        160 2023-06-15               4      NaN        NaT        NaT
160        161 2023-06-15               2      NaN        NaT        NaT
161        162 2023-06-15               3      NaN        NaT        NaT
162        163 2023-06-16               3      NaN        NaT        NaT
163        164 2023-06-16               2      NaN        NaT        NaT
164        165 2023-06-17               2      NaN        NaT        NaT
165        166 2023-06-17               2      NaN        NaT        NaT
166        167 2023-06-17               3      NaN        NaT        NaT
167        168 2023-06-18               7      NaN        NaT        NaT
168        169 2023-06-19               1      NaN        NaT        NaT
169        170 2023-06-19               1      NaN        NaT        NaT
170        171 2023-06-19               1      NaN        NaT        NaT
171        172 2023-06-19               3      NaN        NaT        NaT
172        173 2023-06-19               1      NaN        NaT        NaT
173        174 2023-06-19               4      NaN        NaT        NaT
174        175 2023-06-21               6      NaN        NaT        NaT
175        176 2023-06-21               2      NaN        NaT        NaT
176        177 2023-06-21               2      NaN        NaT        NaT
177        178 2023-06-21               8      NaN        NaT        NaT
178        179 2023-06-21               4      NaN        NaT        NaT
179        180 2023-06-21               2      NaN        NaT        NaT
180        181 2023-06-22               3      NaN        NaT        NaT
181        182 2023-06-22               1      NaN        NaT        NaT
182        183 2023-06-22               2      NaN        NaT        NaT
183        184 2023-06-22               2      NaN        NaT        NaT
184        185 2023-06-22               7      NaN        NaT        NaT
185        186 2023-06-23               3      NaN        NaT        NaT
186        187 2023-06-23               4      NaN        NaT        NaT
187        188 2023-06-23               3      NaN        NaT        NaT
188        189 2023-06-24               3      NaN        NaT        NaT
189        190 2023-06-24               2      NaN        NaT        NaT
190        191 2023-06-26               1      NaN        NaT        NaT
191        192 2023-06-26               4      NaN        NaT        NaT
192        193 2023-06-26               3      NaN        NaT        NaT
193        194 2023-06-26               3      NaN        NaT        NaT
194        195 2023-06-27               4      NaN        NaT        NaT
195        196 2023-06-27               2      NaN        NaT        NaT
196        197 2023-06-27               5      NaN        NaT        NaT
197        198 2023-06-28               4      NaN        NaT        NaT
198        199 2023-06-28               2      NaN        NaT        NaT
199        200 2023-06-29               3      NaN        NaT        NaT
200        201 2023-06-29               1      NaN        NaT        NaT
201        202 2023-06-30               4      NaN        NaT        NaT
202        203 2023-06-30               2      NaN        NaT        NaT
203        204 2023-06-30               3      NaN        NaT        NaT
204        205 2023-07-01               2      NaN        NaT        NaT
205        206 2023-07-01               4      NaN        NaT        NaT
206        207 2023-07-01               2      NaN        NaT        NaT
207        208 2023-07-01               2      NaN        NaT        NaT
208        209 2023-07-02               3      NaN        NaT        NaT
209        210 2023-07-03               4      NaN        NaT        NaT
210        211 2023-07-03               2      NaN        NaT        NaT
211        212 2023-07-03               7      NaN        NaT        NaT
212        213 2023-07-04               5      NaN        NaT        NaT
213        214 2023-07-05               2      NaN        NaT        NaT
214        215 2023-07-07               4      NaN        NaT        NaT
215        216 2023-07-07               1      NaN        NaT        NaT
216        217 2023-07-07               3      NaN        NaT        NaT
217        218 2023-07-07               1      NaN        NaT        NaT
218        219 2023-07-07               1      NaN        NaT        NaT
219        220 2023-07-07               2      NaN        NaT        NaT
220        221 2023-07-08               5      NaN        NaT        NaT
221        222 2023-07-10               1      NaN        NaT        NaT
222        223 2023-07-10               2      NaN        NaT        NaT
223        224 2023-07-11               6      NaN        NaT        NaT
224        225 2023-07-11               5      NaN        NaT        NaT
225        226 2023-07-11               3      NaN        NaT        NaT
226        227 2023-07-12               3      NaN        NaT        NaT
227        228 2023-07-13               1      NaN        NaT        NaT
228        229 2023-07-13               7      NaN        NaT        NaT
229        230 2023-07-13               1      NaN        NaT        NaT
230        231 2023-07-13               1      NaN        NaT        NaT
231        232 2023-07-13               6      NaN        NaT        NaT
232        233 2023-07-13               1      NaN        NaT        NaT
233        234 2023-07-14               7      NaN        NaT        NaT
234        235 2023-07-14               2      NaN        NaT        NaT
235        236 2023-07-14               4      NaN        NaT        NaT
236        237 2023-07-16               3      NaN        NaT        NaT
237        238 2023-07-16               3      NaN        NaT        NaT
238        239 2023-07-16               6      NaN        NaT        NaT
239        240 2023-07-16               4      NaN        NaT        NaT
240        241 2023-07-16               1      NaN        NaT        NaT
241        242 2023-07-17               1      NaN        NaT        NaT
242        243 2023-07-18               1      NaN        NaT        NaT
243        244 2023-07-19               4      NaN        NaT        NaT
244        245 2023-07-19               2      NaN        NaT        NaT
245        246 2023-07-19               2      NaN        NaT        NaT
246        247 2023-07-20               2      NaN        NaT        NaT
247        248 2023-07-20               6      NaN        NaT        NaT
248        249 2023-07-21               5      NaN        NaT        NaT
249        250 2023-07-22               3      NaN        NaT        NaT
250        251 2023-07-22               4      NaN        NaT        NaT
251        252 2023-07-22               3      NaN        NaT        NaT
252        253 2023-07-22               1      NaN        NaT        NaT
253        254 2023-07-22               1      NaN        NaT        NaT
254        255 2023-07-22               4      NaN        NaT        NaT
255        256 2023-07-22               1      NaN        NaT        NaT
256        257 2023-07-23               2      NaN        NaT        NaT
257        258 2023-07-23               5      NaN        NaT        NaT
258        259 2023-07-23               4      NaN        NaT        NaT
259        260 2023-07-24               2      NaN        NaT        NaT
260        261 2023-07-24               2      NaN        NaT        NaT
261        262 2023-07-24               3      NaN        NaT        NaT
262        263 2023-07-24               2      NaN        NaT        NaT
263        264 2023-07-24               2      NaN        NaT        NaT
264        265 2023-07-25               4      NaN        NaT        NaT
265        266 2023-07-25               4      NaN        NaT        NaT
266        267 2023-07-26               2      NaN        NaT        NaT
267        268 2023-07-26               2      NaN        NaT        NaT
268        269 2023-07-27               4      NaN        NaT        NaT
269        270 2023-07-27               4      NaN        NaT        NaT
270        271 2023-07-27               2      NaN        NaT        NaT
271        272 2023-07-27               3      NaN        NaT        NaT

## How many orders were placed outside of promotional periods?

In [9]:
df['promo_id'].isna().sum()

1916