In [1]:
import numpy as np
import pandas as pd

## Load the lesson streaks data

In [2]:
lesson_stats = pd.read_csv('datasets/streak-leaderboard/LessonStreaks.csv', parse_dates=['date'])
lesson_stats

             id  lesson_id       date    user_id        user_name
0       7830319    7643543 2025-05-01  205139497        Ike Pivot
1       7830320   54486981 2025-05-01  210895353    Inosuke Ortiz
2       7830321    6713046 2025-05-01  188456341  Hermione Miller
3       7830322   46804517 2025-05-01  191335864     Piper Palmer
4       7830323   12624656 2025-05-01  188981754    Indy Maverick
...         ...        ...        ...        ...              ...
887514  8736514    7644744 2025-09-28  231934251     Zelda Malfoy
887515  8736515   26637430 2025-09-28  203781955  Jill Brandybuck
887516  8736516   36997603 2025-09-28  197394792   Zara Chartwell
887517  8736517   29534323 2025-09-28  209626625     Mario Banner
887518  8736518   31191502 2025-09-28  231703100      Tifa Kernel

[887519 rows x 5 columns]

## Grab the user and lesson completion date, then remove duplicates

In [3]:
user_streaks = lesson_stats[['user_id', 'user_name', 'date']].drop_duplicates()
user_streaks

          user_id        user_name       date
0       205139497        Ike Pivot 2025-05-01
1       210895353    Inosuke Ortiz 2025-05-01
2       188456341  Hermione Miller 2025-05-01
3       191335864     Piper Palmer 2025-05-01
4       188981754    Indy Maverick 2025-05-01
...           ...              ...        ...
887445  202280044      Sansa Nadal 2025-09-28
887452  232475177  Vincent Thunder 2025-09-28
887457  224658276   Elle Quicksort 2025-09-28
887467  184944578   Kobe Sourdough 2025-09-28
887518  231703100      Tifa Kernel 2025-09-28

[71875 rows x 3 columns]

## Group over consecutive day streaks

In [4]:
indexes = user_streaks.groupby('user_id')['date'].rank(method='min')
date_groups = user_streaks['date'] - pd.to_timedelta(indexes, unit='D')
user_streaks['group'] = date_groups
user_streaks

          user_id        user_name       date      group
0       205139497        Ike Pivot 2025-05-01 2025-04-30
1       210895353    Inosuke Ortiz 2025-05-01 2025-04-30
2       188456341  Hermione Miller 2025-05-01 2025-04-30
3       191335864     Piper Palmer 2025-05-01 2025-04-30
4       188981754    Indy Maverick 2025-05-01 2025-04-30
...           ...              ...        ...        ...
887445  202280044      Sansa Nadal 2025-09-28 2025-08-18
887452  232475177  Vincent Thunder 2025-09-28 2025-09-27
887457  224658276   Elle Quicksort 2025-09-28 2025-09-14
887467  184944578   Kobe Sourdough 2025-09-28 2025-09-07
887518  231703100      Tifa Kernel 2025-09-28 2025-09-24

[71875 rows x 4 columns]

In [5]:
result = user_streaks.groupby(['user_id', 'user_name', 'group'], as_index=False)['date'].agg(
    start_date='min',
    end_date='max',
    streaks='count'
)

## List top 10 longest streaks

In [6]:
result.nlargest(n=10, columns=['streaks'])

         user_id         user_name      group start_date   end_date  streaks
2419    84071240      Stan Pancake 2025-04-30 2025-05-01 2025-09-28      151
32      16814590      Tom Parmesan 2025-05-12 2025-05-31 2025-09-28      121
14987  215518363   Chuck Butternut 2025-05-10 2025-06-01 2025-09-28      120
14928  215468074  Strange Espresso 2025-05-10 2025-06-01 2025-09-26      118
14984  215517194   Maverick Banner 2025-05-10 2025-06-01 2025-09-26      118
14322  213898597       Thor Garcia 2025-05-10 2025-06-01 2025-09-17      109
14934  215471516     Cassie Watson 2025-05-10 2025-06-01 2025-09-17      109
14074  213142099       Helen Melon 2025-05-27 2025-06-25 2025-09-28       96
14739  215121049  Gertrude Strudel 2025-05-11 2025-07-03 2025-09-28       88
28392  225879632     Samus Biscuit 2025-06-23 2025-06-24 2025-09-17       86